return = {
{'M249_Aggressor'},
{'M249_Wolf'},
{'M249_P2020'},
{'M249_Spooky'},
{'M249_Lantern'},
{'M249_Halloween Treats'},
{'AWP_Grepkin'},
{'AWP_Instinct'},
{'AWP_Nerf'},
{'AWP_JTF2'},
{'AWP_Difference'},
{'AWP_Weeb'},
{'AWP_Pink Vision'},
{'AWP_Desert Camo'},
{'AWP_BloxersClub'},
{'AWP_Lunar'},
{'AWP_Scapter'},
{'AWP_Coffin Biter'},
{'AWP_Pear Tree'},
{'AWP_Northern Lights'},
{'AWP_Racer'},
{'AWP_Forever'},
{'AWP_Blastech'},
{'AWP_Abaddon'},
{'AWP_Retroactive'},
{'AWP_Pinkie'},
{'AWP_Autumness'},
{'AWP_Venomus'},
{'AWP_Hika'},
{'AWP_Silence'},
{'AWP_Kumanjayi'},
{'AWP_Dragon'},
{'AWP_Illusion'},
{'AWP_Regina'},
{'AWP_Quicktime'},
{'AWP_Toxic Nitro'},
{'AWP_Darkness'},
{'AWP_Oriental'},
{'AWP_Grim'},
{'AWP_Bloodborne'},
{'Sickle_Mummy'},
{'Sickle_Splattered'},
{'Sickle_Psychadelic'},
{'Sickle_Reaper'},
{'Sickle_Hallows'},
{'Sickle_Hieroglyphs'},
{'Sickle_Static'},
{'Sickle_Crimson'},
{'P2000_Comet'},
{'P2000_Golden Age'},
{'P2000_Apathy'},
{'P2000_Candycorn'},
{'P2000_Lunar'},
{'P2000_Ruby'},
{'P2000_Camo Dipped'},
{'P2000_Dark Beast'},
{'P2000_Pinkie'},
{'P2000_Silence'},
{'Flip Knife_Stock'},
{'Negev_Winterfell'},
{'Negev_Default'},
{'Negev_Quazar'},
{'Negev_Midnightbones'},
{'Negev_Wetland'},
{'Negev_Striped'},
{'Tec9_Gift Wrapped'},
{'Tec9_Ironline'},
{'Tec9_Skintech'},
{'Tec9_Stocking Stuffer'},
{'Tec9_Samurai'},
{'Tec9_Phol'},
{'Tec9_Charger'},
{'Tec9_Performer'},
{'Tec9_Seasoned'},
{'SawedOff_Spooky'},
{'SawedOff_Colorboom'},
{'SawedOff_Casino'},
{'SawedOff_Opal'},
{'SawedOff_Executioner'},
{'SawedOff_Sullys Blacklight'},
{'AUG_Phoenix'},
{'AUG_Dream Hound'},
{'AUG_Enlisted'},
{'AUG_Homestead'},
{'AUG_Sunsthetic'},
{'AUG_NightHawk'},
{'AUG_Maker'},
{'AUG_Graffiti'},
{'AUG_Chilly Night'},
{'AUG_Mystique'},
{'AUG_Soldier'},
{'AUG_Equalizer'},
{'Huntsman Knife_Stock'},
{'Huntsman Knife_Bloodwidow'},
{'Huntsman Knife_Crippled Fade'},
{'Huntsman Knife_Frozen Dream'},
{'Huntsman Knife_Geo Blade'},
{'Huntsman Knife_Hallows'},
{'Huntsman Knife_Marbleized'},
{'Huntsman Knife_Naval'},
{'Huntsman Knife_Ruby'},
{'Huntsman Knife_Splattered'},
{'Huntsman Knife_Wetland'},
{'Huntsman Knife_Monster'},
{'Huntsman Knife_Cozy'},
{'Huntsman Knife_Cosmos'},
{'Huntsman Knife_Digital'},
{'Huntsman Knife_Tropical'},
{'Huntsman Knife_Crimson Tiger'},
{'Huntsman Knife_Worn'},
{'Huntsman Knife_Egg Shell'},
{'Huntsman Knife_Twitch'},
{'Huntsman Knife_Honor Fade'},
{'Huntsman Knife_Consumed'},
{'Huntsman Knife_Goo'},
{'Huntsman Knife_Wrapped'},
{'Huntsman Knife_Aurora'},
{'Huntsman Knife_Ciro'},
{'Huntsman Knife_Drop-Out'},
{'Huntsman Knife_Spirit'},
{'Huntsman Knife_Spookiness'},
{'FiveSeven_Stigma'},
{'FiveSeven_Summer'},
{'FiveSeven_Gifted'},
{'FiveSeven_Midnight Ride'},
{'FiveSeven_Fluid'},
{'FiveSeven_Sub Zero'},
{'FiveSeven_Autumn Fade'},
{'FiveSeven_Mr. Anatomy'},
{'FiveSeven_Danjo'},
{'FiveSeven_Accelerator'},
{'Falchion Classic_Late Night'},
{'DesertEagle_Glittery'},
{'DesertEagle_Grim'},
{'DesertEagle_Weeb'},
{'DesertEagle_Krystallos'},
{'DesertEagle_Honor-bound'},
{'DesertEagle_TC'},
{'DesertEagle_Xmas'},
{'DesertEagle_Scapter'},
{'DesertEagle_Cool Blue'},
{'DesertEagle_Survivor'},
{'DesertEagle_Ababa'},
{'DesertEagle_Heat'},
{'DesertEagle_ROLVe'},
{'DesertEagle_Independence'},
{'DesertEagle_Racer'},
{'DesertEagle_Pumpkin Buster'},
{'DesertEagle_Skin Committee'},
{'DesertEagle_DropX'},
{'DesertEagle_Crystal'},
{'DesertEagle_Blue Fur'},
{'DesertEagle_Cold Truth'},
{'DesertEagle_BloxersClub'},
{'DesertEagle_Guapo'},
{'DesertEagle_Regal Eclipse'},
{'G3SG1_Foliage'},
{'G3SG1_Hex'},
{'G3SG1_Amethyst'},
{'G3SG1_Autumn'},
{'G3SG1_Mahogany'},
{'G3SG1_Holly Bound'},
{'Karambit_Stock'},
{'Karambit_Bloodwidow'},
{'Karambit_Crippled Fade'},
{'Karambit_Frozen Dream'},
{'Karambit_Gold'},
{'Karambit_Hallows'},
{'Karambit_Jade Dream'},
{'Karambit_Marbleized'},
{'Karambit_Naval'},
{'Karambit_Ruby'},
{'Karambit_Splattered'},
{'Karambit_Twitch'},
{'Karambit_Wetland'},
{'Karambit_Scapter'},
{'Karambit_Lantern'},
{'Karambit_Glossed'},
{'Karambit_Cosmos'},
{'Karambit_Digital'},
{'Karambit_Topaz'},
{'Karambit_Crimson Tiger'},
{'Karambit_Egg Shell'},
{'Karambit_Worn'},
{'Karambit_Tropical'},
{'Karambit_Neonic'},
{'Karambit_Liberty Camo'},
{'Karambit_Ghost'},
{'Karambit_Consumed'},
{'Karambit_Goo'},
{'Karambit_Death Wish'},
{'Karambit_Pizza'},
{'Karambit_Festive'},
{'Karambit_Quicktime'},
{'Karambit_Racer'},
{'Karambit_Jester'},
{'Karambit_Ciro'},
{'Karambit_Drop-Out'},
{'Karambit_Peppermint'},
{'Karambit_Cob Web'},
{'USP_Skull'},
{'USP_Yellowbelly'},
{'USP_Crimson'},
{'USP_Jade Dream'},
{'USP_Racing'},
{'USP_Frostbite'},
{'USP_Nighttown'},
{'USP_Paradise'},
{'USP_Dizzy'},
{'USP_Kraken'},
{'USP_Worlds Away'},
{'USP_Unseen'},
{'USP_Holiday'},
{'USP_Survivor'},
{'USP_BloxersClub'},
{'USP_Blossom'},
{'MAC10_Pimpin'},
{'MAC10_Wetland'},
{'MAC10_Turbo'},
{'MAC10_Golden Rings'},
{'MAC10_Skeleboney'},
{'MAC10_Artists Intent'},
{'MAC10_Toxic'},
{'MAC10_Blaze'},
{'MAC10_Scythe'},
{'MAC10_Devil'},
{'MAC10_Energy'},
{'Glock_Desert Camo'},
{'Glock_Day Dreamer'},
{'Glock_Wetland'},
{'Glock_Anubis'},
{'Glock_Midnight Tiger'},
{'Glock_Scapter'},
{'Glock_Gravestomper'},
{'Glock_Tarnish'},
{'Glock_Rush'},
{'Glock_Angler'},
{'Glock_Spacedust'},
{'Glock_Money Maker'},
{'Glock_RSL'},
{'Glock_White Sauce'},
{'Glock_Biotrip'},
{'Glock_Underwater'},
{'Glock_Hallows'},
{'Glock_BloxersClub'},
{'Fingerless Glove_Kimura'},
{'Fingerless Glove_Spookiness'},
{'Fingerless Glove_Patch'},
{'Fingerless Glove_Digital'},
{'Fingerless Glove_Scapter'},
{'Fingerless Glove_Crystal'},
{'MP7_Sunshot'},
{'MP7_Calaxian'},
{'MP7_Goo'},
{'MP7_Holiday'},
{'MP7_Silent Ops'},
{'MP7_Industrial'},
{'MP7_Reindeer'},
{'MP7_Cogged'},
{'MP7_Trauma'},
{'AK47_Hallows'},
{'AK47_Ace'},
{'AK47_Code Orange'},
{'AK47_Clown'},
{'AK47_Variant Camo'},
{'AK47_Eve'},
{'AK47_VAV'},
{'AK47_Quantum'},
{'AK47_Hypersonic'},
{'AK47_Mean Green'},
{'AK47_Bloodboom'},
{'AK47_Scapter'},
{'AK47_Skin Committee'},
{'AK47_Patch'},
{'AK47_Outlaws'},
{'AK47_Gifted'},
{'AK47_Ugly Sweater'},
{'AK47_Secret Santa'},
{'AK47_Precision'},
{'AK47_Outrunner'},
{'AK47_Godess'},
{'AK47_Maker'},
{'AK47_Ghost'},
{'AK47_Glo'},
{'AK47_Survivor'},
{'AK47_Shooting Star'},
{'AK47_Halo'},
{'AK47_Inversion'},
{'AK47_Plated'},
{'AK47_Quicktime'},
{'AK47_Yltude'},
{'AK47_Trinity'},
{'AK47_Toxic Nitro'},
{'AK47_Scythe'},
{'AK47_Neonline'},
{'AK47_Galaxy Corpse'},
{'AK47_Weeb'},
{'AK47_Super Weeb'},
{'AK47_BloxersClub'},
{'AK47_Jester'},
{'Galil_Hardware'},
{'Galil_Hardware 2'},
{'Galil_Toxicity'},
{'Galil_Frosted'},
{'Galil_Worn'},
{'Galil_Vortex'},
{'Butterfly Knife_Stock'},
{'Butterfly Knife_Bloodwidow'},
{'Butterfly Knife_Crippled Fade'},
{'Butterfly Knife_Frozen Dream'},
{'Butterfly Knife_Hallows'},
{'Butterfly Knife_Jade Dream'},
{'Butterfly Knife_Marbleized'},
{'Butterfly Knife_Naval'},
{'Butterfly Knife_Ruby'},
{'Butterfly Knife_Splattered'},
{'Butterfly Knife_Twitch'},
{'Butterfly Knife_Wetland'},
{'Butterfly Knife_White Boss'},
{'Butterfly Knife_Scapter'},
{'Butterfly Knife_Reaper'},
{'Butterfly Knife_Icicle'},
{'Butterfly Knife_Cosmos'},
{'Butterfly Knife_Digital'},
{'Butterfly Knife_Topaz'},
{'Butterfly Knife_Tropical'},
{'Butterfly Knife_Crimson Tiger'},
{'Butterfly Knife_Egg Shell'},
{'Butterfly Knife_Worn'},
{'Butterfly Knife_Neonic'},
{'Butterfly Knife_Freedom'},
{'Butterfly Knife_Consumed'},
{'Butterfly Knife_Goo'},
{'Butterfly Knife_Inversion'},
{'Butterfly Knife_Wrapped'},
{'Butterfly Knife_Aurora'},
{'Butterfly Knife_Argus'},
{'Butterfly Knife_Snowfall'},
{'Butterfly Knife_Spooky'},
{'Strapped Glove_Cob Web'},
{'Strapped Glove_Kringle'},
{'Strapped Glove_Molten'},
{'Strapped Glove_Wisk'},
{'Strapped Glove_Grim'},
{'Strapped Glove_Racer'},
{'Strapped Glove_Drop-Out'},
{'Strapped Glove_BloxersClub'},
{'Sports Glove_Pumpkin'},
{'Sports Glove_CottonTail'},
{'Sports Glove_RSL'},
{'Sports Glove_Skulls'},
{'Sports Glove_Weeb'},
{'Sports Glove_Royal'},
{'Sports Glove_Majesty'},
{'Sports Glove_Hallows'},
{'Sports Glove_Hazard'},
{'Sports Glove_Calamity'},
{'Sports Glove_Twitch'},
{'Sports Glove_Dead Prey'},
{'MAG7_Molten'},
{'MAG7_Striped'},
{'MAG7_Frosty'},
{'MAG7_Outbreak'},
{'MAG7_Bombshell'},
{'MAG7_C4UTION'},
{'Handwraps_Mummy'},
{'Handwraps_Toxic Nitro'},
{'Handwraps_Green Hex'},
{'Handwraps_Purple Hex'},
{'Handwraps_Orange Hex'},
{'Handwraps_Spector Hex'},
{'Handwraps_Phantom Hex'},
{'Handwraps_Microbes'},
{'Handwraps_Wetland'},
{'Handwraps_Guts'},
{'Handwraps_Wraps'},
{'Handwraps_MMA'},
{'Handwraps_Ghoul Hex'},
{'XM_Red'},
{'XM_Spectrum'},
{'XM_Artic'},
{'XM_Atomic'},
{'XM_Campfire'},
{'XM_Predator'},
{'XM_MK11'},
{'XM_Endless Night'},
{'UMP_Militia Camo'},
{'UMP_Magma'},
{'UMP_Redline'},
{'UMP_Death Grip'},
{'UMP_Molten'},
{'UMP_Gum Drop'},
{'UMP_Orbit'},
{'Crowbar_Stock'},
{'M4A1_Toucan'},
{'M4A1_Animatic'},
{'M4A1_Desert Camo'},
{'M4A1_Wastelander'},
{'M4A1_BloxersClub'},
{'M4A1_Tecnician'},
{'M4A1_Impulse'},
{'M4A1_Burning'},
{'M4A1_Lunar'},
{'M4A1_Necropolis'},
{'M4A1_Jester'},
{'M4A1_Nightmare'},
{'M4A1_Heavens Gate'},
{'Scout_Xmas'},
{'Scout_Coffin Biter'},
{'Scout_Railgun'},
{'Scout_Hellborn'},
{'Scout_Hot Cocoa'},
{'Scout_Theory'},
{'Scout_Pulse'},
{'Scout_Monstruo'},
{'Scout_Flowing Mists'},
{'Scout_Neon Regulation'},
{'Scout_Posh'},
{'Scout_Darkness'},
{'Scout_Lunar'},
{'CZ_Lightning'},
{'CZ_Orange Web'},
{'CZ_Festive'},
{'CZ_Spectre'},
{'CZ_Designed'},
{'CZ_Holidays'},
{'CZ_Hallow'},
{'Falchion Knife_Stock'},
{'Falchion Knife_Bloodwidow'},
{'Falchion Knife_Chosen'},
{'Falchion Knife_Crippled Fade'},
{'Falchion Knife_Frozen Dream'},
{'Falchion Knife_Hallows'},
{'Falchion Knife_Marbleized'},
{'Falchion Knife_Naval'},
{'Falchion Knife_Ruby'},
{'Falchion Knife_Splattered'},
{'Falchion Knife_Wetland'},
{'Falchion Knife_Zombie'},
{'Falchion Knife_Coal'},
{'Falchion Knife_Late Night'},
{'Falchion Knife_Cosmos'},
{'Falchion Knife_Digital'},
{'Falchion Knife_Topaz'},
{'Falchion Knife_Tropical'},
{'Falchion Knife_Crimson Tiger'},
{'Falchion Knife_Egg Shell'},
{'Falchion Knife_Worn'},
{'Falchion Knife_Neonic'},
{'Falchion Knife_Consumed'},
{'Falchion Knife_Freedom'},
{'Falchion Knife_Goo'},
{'Falchion Knife_Inversion'},
{'Falchion Knife_Wrapped'},
{'Falchion Knife_Festive'},
{'Falchion Knife_Racer'},
{'Falchion Knife_Toxic Nitro'},
{'Falchion Knife_Pumpkin'},
{'Falchion Knife_Cocoa'},
{'Falchion Knife_Kimura'},
{'Falchion Knife_Twilight'},
{'M4A4_Devil'},
{'M4A4_Pinkvision'},
{'M4A4_Desert Camo'},
{'M4A4_BOT[S]'},
{'M4A4_Precision'},
{'M4A4_Candyskull'},
{'M4A4_Scapter'},
{'M4A4_Toy Soldier'},
{'M4A4_Endline'},
{'M4A4_Pondside'},
{'M4A4_Ice Cap'},
{'M4A4_Pinkie'},
{'M4A4_Racer'},
{'M4A4_Stardust'},
{'M4A4_King'},
{'M4A4_Flashy Ride'},
{'M4A4_RayTrack'},
{'M4A4_Mistletoe'},
{'M4A4_Delinquent'},
{'M4A4_Quicktime'},
{'M4A4_Jester'},
{'M4A4_Darkness'},
{'MP9_Velvita'},
{'MP9_Blueroyal'},
{'MP9_Decked Halls'},
{'MP9_Cookie Man'},
{'MP9_Wilderness'},
{'MP9_Vaporwave'},
{'MP9_Cob Web'},
{'MP9_SnowTime'},
{'MP9_Control'},
{'P90_Skulls'},
{'P90_Redcopy'},
{'P90_Demon Within'},
{'P90_P-Chan'},
{'P90_Krampus'},
{'P90_Pine'},
{'P90_Elegant'},
{'P90_Northern Lights'},
{'P90_Argus'},
{'P90_Curse'},
{'SG_Yltude'},
{'SG_Knighthood'},
{'SG_Variant Camo'},
{'SG_Magma'},
{'SG_DropX'},
{'SG_Dummy'},
{'SG_Kitty Cat'},
{'SG_Drop-Out'},
{'SG_Control'},
{'SG_NR8'},
{'Gut Knife_Bloodwidow'},
{'Gut Knife_Crippled Fade'},
{'Gut Knife_Frozen Dream'},
{'Gut Knife_Geo Blade'},
{'Gut Knife_Present'},
{'Gut Knife_Marbleized'},
{'Gut Knife_Naval'},
{'Gut Knife_Ruby'},
{'Gut Knife_Rusty'},
{'Gut Knife_Splattered'},
{'Gut Knife_Wetland'},
{'Gut Knife_Lurker'},
{'Gut Knife_Hallows'},
{'Gut Knife_Cosmos'},
{'Gut Knife_Digital'},
{'Gut Knife_Topaz'},
{'Gut Knife_Tropical'},
{'Gut Knife_Crimson Tiger'},
{'Gut Knife_Egg Shell'},
{'Gut Knife_Worn'},
{'Gut Knife_Neonic'},
{'Gut Knife_Banner'},
{'Gut Knife_Consumed'},
{'Gut Knife_Goo'},
{'Gut Knife_Wrapped'},
{'Gut Knife_Holly'},
{'Gut Knife_Cob Web'},
{'R8_Violet'},
{'R8_Hunter'},
{'R8_Spades'},
{'R8_Exquisite'},
{'R8_TG'},
{'P250_BloxersClub'},
{'P250_Green Web'},
{'P250_TC250'},
{'P250_Amber'},
{'P250_Frosted'},
{'P250_Solstice'},
{'P250_Equinox'},
{'P250_Goldish'},
{'P250_Shark'},
{'P250_Midnight'},
{'P250_Bomber'},
{'Nova_Terraformer'},
{'Nova_Tiger'},
{'Nova_Black Ice'},
{'Nova_Sharkesh'},
{'Nova_Paradise'},
{'Nova_Starry Night'},
{'Nova_Cookie'},
{'Nova_Tricked'},
{'Nova_Defective'},
{'Nova_Oath'},
{'Bearded Axe_Beast'},
{'Bearded Axe_Splattered'},
{'Cleaver_Spider'},
{'Cleaver_Splattered'},
{'Cleaver_ImageLabel'},
{'Bayonet_Stock'},
{'Bayonet_Frozen Dream'},
{'Bayonet_Geo Blade'},
{'Bayonet_Hallows'},
{'Bayonet_Intertwine'},
{'Bayonet_Marbleized'},
{'Bayonet_Naval'},
{'Bayonet_Sapphire'},
{'Bayonet_Splattered'},
{'Bayonet_Twitch'},
{'Bayonet_Wetland'},
{'Bayonet_Easy-Bake'},
{'Bayonet_Crow'},
{'Bayonet_UFO'},
{'Bayonet_Silent Night'},
{'Bayonet_Ciro'},
{'Bayonet_Digital'},
{'Bayonet_Topaz'},
{'Bayonet_Tropical'},
{'Bayonet_Crimson Tiger'},
{'Bayonet_Egg Shell'},
{'Bayonet_Worn'},
{'Bayonet_Neonic'},
{'Bayonet_RSL'},
{'Bayonet_Consumed'},
{'Bayonet_Banner'},
{'Bayonet_Goo'},
{'Bayonet_Ghastly'},
{'Bayonet_Candy Cane'},
{'Bayonet_Mariposa'},
{'Bayonet_Aequalis'},
{'Bayonet_Festive'},
{'Bayonet_Wrapped'},
{'Bayonet_Delinquent'},
{'Bayonet_Racer'},
{'Bayonet_Decor'},
{'Bayonet_Kimura'},
{'Bayonet_Haunted'},
{'Bayonet_BloxersClub'},
{'Bayonet_Cosmos'},
{'Famas_Abstract'},
{'Famas_Haunted Forest'},
{'Famas_Goliath'},
{'Famas_Redux'},
{'Famas_Toxic Rain'},
{'Famas_Centipede'},
{'Famas_Medic'},
{'Famas_Cogged'},
{'Famas_KugaX'},
{'Famas_Shocker'},
{'Famas_MK11'},
{'Famas_Imprisioned'},
{'Famas_Blossom'},
{'Bizon_Festive'},
{'Bizon_Shattered'},
{'Bizon_Oblivion'},
{'Bizon_Sergeant'},
{'Bizon_Saint Nick'},
{'Bizon_Autumic'},
}
